### ISSUE TITLE
Wheat

### ISSUE THREAD

**Issue by mattpardee** [Aaronontheweb/node-bootcamp#49]
Were there any intentions of putting this repo into [Wheat](https://github.com/creationix/wheat)?

Trust that this isn't an attempt to add more work&lt;g&gt; but rather as a problem solver: instead of having this loose connection of articles with no UX (GitHub is not UX), Wheat will allow us to create a navigation flow _and_ demonstrate an example of a node-powered website. It's the best example of dogfooding, and the audience will pick up on it right away.

Even better? Use Cloud9 to deploy the docs to an Azure account (that we're all a member of) - thus the site will come to life at nodebootcamp.cloudapp.com.

I have a lot more ideas surrounding this but this creates a much better user experience than just making this repo public. I understand this is a bit late, but I'm willing to throw my 800 lb gorilla weight behind this on Monday.

**Comment by mattpardee** [comment]
I suppose the first question I should've asked: is there a Microsoft sponsored landing page for these bootcamps already?

**Comment by Aaronontheweb** [comment]
Matt,

I'm down to put all of this into Wheat - here's my though process behind this:
1. Get the content done in Github first; I don't want Github to be the presentation medium, but it's a great collaboration medium for while we're working.
2. By Wednesday next week, start re-rendering everything into presentation format. 
3. Have presentation content finished by Midday Friday and do a rehearsal before Node Bootcamp Santa Monica starts.

So yeah, I think using Wheat is a great idea and want to do it, but we need that content done first ;)

**Comment by patrickfoley** [comment]
Gotta say - I'm totally diggin the process you guys used for this. Thanks for including me.
